"""
Django settings for Email project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import pymysql
pymysql.install_as_MySQLdb()


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a%n0+xynpz6(gq5bjsgrhr9%c%m&by8^=oszb&c_@!4v^g!jv^'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'mails.apps.MailsConfig',
    'import_export',
    'easy_pdf',
    'mails',
    'users',


    #'smsish',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'Email.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Email.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'email',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

MEDIA_URL = '/media/'
# La Bonne version
STATIC_URL = '/static/'
STATIC_PATH = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
    STATIC_PATH,
)


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR + '/media/'



LOGIN_REDIRECT_URL='login'




































# Configuration d'envoie SMS

# Send sms en mode console
#SENDSMS_BACKEND = 'sendsms.backends.console.SmsBackend'

#SENDSMS_BACKEND = 'mails.mysmsbackend.SmsBackend'



#SMS_BACKEND_CONSOLE = 'smsish.sms.backends.console.SMSBackend'
#SMS_BACKEND_DUMMY = 'smsish.sms.backends.dummy.SMSBackend'
#SMS_BACKEND_TWILIO = 'smsish.sms.backends.twilio.SMSBackend'
#SMS_BACKEND = SMS_BACKEND_DUMMY


#TWILIO_ACCOUNT_SID = 'AC2db9b37a818f6e07945304aaa7eba0df'
#TWILIO_AUTH_TOKEN = '235326af90061c1bdf30af81c594452f'

#TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", None)
#TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", None)

#TWILIO_ACCOUNT_SID = os.getenv("AC2db9b37a818f6e07945304aaa7eba0df", None)
#TWILIO_AUTH_TOKEN = os.getenv("235326af90061c1bdf30af81c594452f", None)

#TWILIO_MAGIC_FROM_NUMBER = "+15005550006"  # This number passes all validation.
#TWILIO_MAGIC_FROM_NUMBER = "+221771096893"  # This number passes all validation.
#TWILIO_FROM_NUMBER = os.getenv("TWILIO_FROM_NUMBER", TWILIO_MAGIC_FROM_NUMBER)


























































# Configuration de l'envoie d'email


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_FILE_PATH = '/static/'
#EMAIL_PORT = 25
EMAIL_PORT = 587
EMAIL_HOST_USER = 'aliounemane2@gmail.com'
EMAIL_HOST_PASSWORD = '771096893'
EMAIL_USE_TLS = True
FILE_CHARSET = 'utf-8'
DEFAULT_FROM_EMAIL = 'NEMA - GROUP <aliounemane2@gmail.com>'