# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinataire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('adresse', models.EmailField(max_length=175)),
            ],
        ),
        migrations.CreateModel(
            name='Destinataire_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.Destinataire')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('destinataire', models.ManyToManyField(through='mails.Destinataire_Group', to='mails.Destinataire')),
            ],
        ),
        migrations.AddField(
            model_name='destinataire_group',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.Group'),
        ),
    ]
